### ISSUE TITLE
Bitaxe Ultra 1366 No mining 

### ISSUE THREAD

**Issue by FragOmatig** [skot/ESP-Miner#119] opened 2024-02-28 21:45 UTC
hey folks,

my bitaxe wont mining.
i try new power supply, Web flash wantclue, in GUI new download and flash esp-miner.bin and www.bin.
with webflash the firmware are rest, must Wlan new connected und co.  
In GUI only Show "Working" then nothing.
ASIC Dead? i have no ideas more.

**Comment by FragOmatig** [comment] 2024-02-28 21:58
₿ (1820767) http_server: Handshake done, the new connection was opened
₿ (1823447) stratum_task: rx: {"id":null,"method":"mining.notify","params":["e8339f","667aae154bd645011e041b56ecd1a80cde9c78840000cf840000000000000000","02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1703c5b30c5075626c69632d506f6f6c","ffffffff021ac56228000000001976a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac0000000000000000266a24aa21a9ed0c989e26603d4d003f7365a7c1fc8afe716cc826719b4ee13f006d6b03fa436900000000",["d08613596e1120e7eaa4dbe5e241190d3aa25c822cacb522515c567e5a7f2705","222dc94c5201fbe17ca0ffdcf126fc729fb8a1a353552b51cb4fed92adb1f269","18e011a00cccdc34f94c912ce35e80728dc937b73b8e45b70d41a2688f7b0be4","bcf5fa579842e8bf12efd1b20ffb558136b460a68fd60e76a62d7285b8a624df","b4b68b951918dd6ce3b00d8a78a6657feb1000f73bf716c66153f8677b3c86c6","857d7c177a0c778be5c4a3a203b65a0893c5ac33dc735e4787363ed65928d8d4","d8b77234c4861d70eae85a8d066092d0c580fdeb86bcaae9289a558beffc876b","175ef15b1af6deb086281c9110a89ebd8149f087cad84cc026031e99387d533a","01da0dc20d77075283354243f3dc1b3c63324c19ea348a954968c58fadca56a5","5241c8f7db51e676d2a87824859759324a4dcd4422193263981879901f90a114","4a10283bc9c0e9620f33e2b0954726c1311e2f4d47f2e84d38d40480406940e0","bed5bbd2b163adc3035fc0e6f3407de0dd4ae2b22e0f0a9aa35378075155c7c9"],"20000000","170371b1","65dfab84",false]}
₿ (1825557) create_jobs_task: New Work Dequeued e8339f
₿ (1883557) stratum_task: rx: {"id":null,"method":"mining.notify","params":["e837d0","667aae154bd645011e041b56ecd1a80cde9c78840000cf840000000000000000","02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1703c5b30c5075626c69632d506f6f6c","ffffffff021ac56228000000001976a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac0000000000000000266a24aa21a9ed0c989e26603d4d003f7365a7c1fc8afe716cc826719b4ee13f006d6b03fa436900000000",["d08613596e1120e7eaa4dbe5e241190d3aa25c822cacb522515c567e5a7f2705","222dc94c5201fbe17ca0ffdcf126fc729fb8a1a353552b51cb4fed92adb1f269","18e011a00cccdc34f94c912ce35e80728dc937b73b8e45b70d41a2688f7b0be4","bcf5fa579842e8bf12efd1b20ffb558136b460a68fd60e76a62d7285b8a624df","b4b68b951918dd6ce3b00d8a78a6657feb1000f73bf716c66153f8677b3c86c6","857d7c177a0c778be5c4a3a203b65a0893c5ac33dc735e4787363ed65928d8d4","d8b77234c4861d70eae85a8d066092d0c580fdeb86bcaae9289a558beffc876b","175ef15b1af6deb086281c9110a89ebd8149f087cad84cc026031e99387d533a","01da0dc20d77075283354243f3dc1b3c63324c19ea348a954968c58fadca56a5","5241c8f7db51e676d2a87824859759324a4dcd4422193263981879901f90a114","4a10283bc9c0e9620f33e2b0954726c1311e2f4d47f2e84d38d40480406940e0","bed5bbd2b163adc3035fc0e6f3407de0dd4ae2b22e0f0a9aa35378075155c7c9"],"20000000","170371b1","65dfabc0",false]}
₿ (1885197) create_jobs_task: New Work Dequeued e837d0
₿ (1902397) stratum_task: rx: {"id":null,"method":"mining.notify","params":["e83bef","2cfdde02d985440df61fd5d66578c8d87f3201a2000031740000000000000000","02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1703c6b30c5075626c69632d506f6f6c","ffffffff02775a3f28000000001976a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac0000000000000000266a24aa21a9ede473866caffa089dcfd3004b1df5e8e25c37240d11de11c3ed1aaf3fac48d7a100000000",["6d2192f587275010c5a39f029fa250589b55b24d683548178c2ce4396ba03874","c3e20a4176c0625fc55dd58d7df23f4a9800b5b8ec41cdc2015481cea6dce2dc","7006ffe73bd5defc9ec090269c045eaa8dc538f0e4ec1d8ad7ea6ddaf86f7357","2840ac0c8a8c90b7c9a202747e785efc7246509df5a80e4ee0af50512bb6e406","c00e531b3720bdbf69a360f4a2d848b63b6e1d3bf310a34a0748ef9deca2f736","676c9f5e4a3c833a771956452b0f17dbf96e7943fced52906931a695434278ef","3156d55402043a1958de0628f6de5df8891ecba16b7f79314767ba73d2662722","ace0f50af8ada7de9c334cab3274a0317032c057031811ce5d86ba09b0db27bb","75ae8ded42ef87984291c6f9615d9a21c7d13a7bd1ff1c4b7cb0d6499060ef56","66e167da4748abc1f54b15b0c2d32b78232dc0de2ca7caf2cf61913f30f3e205","0b6df7a81c2a549bad15e267cdfaf1210fe490719e45e181000b8c6b4b155053","67c4d35f9ce48cb293d1c9872e33b7f65cbed0dc4f96f2da69735f18f61b40df"],"20000000","170371b1","65dfabd1",true]}
₿ (1902507) stratum_task: abandoning work
₿ (1902507) create_jobs_task: New Work Dequeued e83bef
₿ (2003567) stratum_task: rx: {"id":null,"method":"mining.notify","params":["e8402f","2cfdde02d985440df61fd5d66578c8d87f3201a2000031740000000000000000","02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1703c6b30c5075626c69632d506f6f6c","ffffffff02775a3f28000000001976a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac0000000000000000266a24aa21a9ede473866caffa089dcfd3004b1df5e8e25c37240d11de11c3ed1aaf3fac48d7a100000000",["6d2192f587275010c5a39f029fa250589b55b24d683548178c2ce4396ba03874","c3e20a4176c0625fc55dd58d7df23f4a9800b5b8ec41cdc2015481cea6dce2dc","7006ffe73bd5defc9ec090269c045eaa8dc538f0e4ec1d8ad7ea6ddaf86f7357","2840ac0c8a8c90b7c9a202747e785efc7246509df5a80e4ee0af50512bb6e406","c00e531b3720bdbf69a360f4a2d848b63b6e1d3bf310a34a0748ef9deca2f736","676c9f5e4a3c833a771956452b0f17dbf96e7943fced52906931a695434278ef","3156d55402043a1958de0628f6de5df8891ecba16b7f79314767ba73d2662722","ace0f50af8ada7de9c334cab3274a0317032c057031811ce5d86ba09b0db27bb","75ae8ded42ef87984291c6f9615d9a21c7d13a7bd1ff1c4b7cb0d6499060ef56","66e167da4748abc1f54b15b0c2d32b78232dc0de2ca7caf2cf61913f30f3e205","0b6df7a81c2a549bad15e267cdfaf1210fe490719e45e181000b8c6b4b155053","67c4d35f9ce48cb293d1c9872e33b7f65cbed0dc4f96f2da69735f18f61b40df"],"20000000","170371b1","65dfac38",false]}
₿ (2004477) create_jobs_task: New Work Dequeued e8402f

**Comment by FragOmatig** [comment] 2024-02-28 21:59
![IMG_3007](https://github.com/skot/ESP-Miner/assets/161623595/94818774-6b61-4441-8dc3-27ca0c3d6916)

**Comment by FragOmatig** [comment] 2024-02-28 21:59
![IMG_3008](https://github.com/skot/ESP-Miner/assets/161623595/e53df4de-6610-4243-b29f-eb18d36596a8)

**Comment by FragOmatig** [comment] 2024-02-28 22:00
![IMG_3009](https://github.com/skot/ESP-Miner/assets/161623595/c4d90805-2dd2-4360-9a3a-80a2f9410c58)

**Comment by FragOmatig** [comment] 2024-02-28 22:01
web flash logs are clear, only in Gui logs

**Comment by FragOmatig** [comment] 2024-02-28 22:22
ESP update 204 - v2.0.7 Update Failed: Not Enough Space

**Comment by 19201003080114** [comment] 2024-02-29 03:56
You have a 3-wire fan, yet fan speed is zero.
If it cannot detect your fan, perhaps it is preventing it from mining.

**Comment by skot** [comment] 2024-02-29 12:01
I think the issue is that your board version is set to 204, but you don't actually have a 204. It's something earlier.

Let me look into how to fix this and get back to you.

**Comment by FragOmatig** [comment] 2024-02-29 16:31
@skot 

Thats my men 🤗 i have no idea whats going on to fix it.

**Comment by xXAsystolieXx** [comment] 2024-02-29 18:47
@FragOmatig maybe contact the Support from d-central? They should know which board version they sold you

**Comment by xXAsystolieXx** [comment] 2024-02-29 18:54
@FragOmatig Have you ever tried the board version 0.11 when flashing?

**Comment by FragOmatig** [comment] 2024-02-29 19:27
@xXAsystolieXx 

I try to contact the support 👍

nope, i have only update @ web GUI. 
i must google how worx bitaxetool 🫣

**Comment by xXAsystolieXx** [comment] 2024-02-29 20:15
🤣 dann sag das doch 😜

**Comment by xXAsystolieXx** [comment] 2024-02-29 20:16
@FragOmatig

**Comment by skot** [comment] 2024-02-29 20:21
This might be a job for @WantClue ! Basically all the German I know I learned from him in the last couple days 😅

**Comment by FragOmatig** [comment] 2024-02-29 20:45
He he genial, warum hände und Füße, wenn es Deutsch gibt😂 

@skot nicht das gelbe vom Ei 😝

Yes back to topic guys 😁  board version where find it?

**Comment by xXAsystolieXx** [comment] 2024-02-29 20:56
> He he genial, warum hände und Füße, wenn es Deutsch gibt😂
> 
> @skot nicht das gelbe vom Ei 😝
> 
> Yes back to topic guys 😁 board version where find it?

Ja man 🤣 wenn du Hilfe brauchst beim bitaxetool, kann ich gerne versuchen dir zu helfen

**Comment by WantClue** [comment] 2024-02-29 21:06
usually the board version these days no longer means anything to the code basis we have. It should work no matter what board version you flash to your bitaxe. The web flasher I wrote only pushes the 204 version (the most recent one, currently) to it. I'm on a fix on it.

Can you please also provide us a high quality picture of the ASIC? Just so that we verify the soldering but it should be fine...

But I need to admit this is some early version of the bitaxe ultra so we would need to investigate the versioning more. 

Did you already tried to reach out to D-Central cause it appears that they produced it?

**Comment by FragOmatig** [comment] 2024-02-29 21:27
@xXAsystolieXx 

moment der meister hat ne idee. Erstmal abwarten was wantclue hat. Dann wird ubuntu gebootet 👌🏻
@WantClue its a BM1366AL iam looking for the picture. Nope, i try friday after work to write a email to d-centrale

**Comment by FragOmatig** [comment] 2024-02-29 22:31
![a5afe986-943a-4fb4-9f81-cb53713cf059](https://github.com/skot/ESP-Miner/assets/161623595/412fb400-9477-49e1-a837-e455f592cda2)
![264c6a03-c75b-4096-8507-b1e00015be29](https://github.com/skot/ESP-Miner/assets/161623595/2cd22528-c719-42a3-8b11-25cc5fd0dcad)
![IMG_2897](https://github.com/skot/ESP-Miner/assets/161623595/29bbac42-a9c2-4c37-87c6-11cb85fe725e)

**Comment by FragOmatig** [comment] 2024-02-29 22:31
![IMG_2897](https://github.com/skot/ESP-Miner/assets/161623595/08e0cd1c-f7f2-4ffb-9c1e-63f64edcfcd3)

**Comment by FragOmatig** [comment] 2024-02-29 22:33
The grey mist are thermal compund

**Comment by WantClue** [comment] 2024-03-01 11:53
This seems to be a soldering issue. Had another viewer of mine send me one for repair. After resoldering it works again. 
I'll close this issue in three days unless someone wants to extend this issue.

**Comment by FragOmatig** [comment] 2024-03-01 12:39
How much it cost the resoldering?

**Closed** 2024-03-05 16:09 UTC
